// <auto-generated />
using System;
using MagicWall.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicWall.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929151826_LinkCandidatesToSeats")]
    partial class LinkCandidatesToSeats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MagicWall.Api.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Budget.BudgetSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAllocation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear", "Name")
                        .IsUnique();

                    b.ToTable("BudgetSectors", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetSector_Allocation", "TotalAllocation >= 0");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Budget.MegaProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BudgetAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("BudgetSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("GeoLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetSectorId");

                    b.ToTable("MegaProjects", t =>
                        {
                            t.HasCheckConstraint("CK_MegaProject_Amount", "BudgetAmount >= 0");

                            t.HasCheckConstraint("CK_MegaProject_Completion", "CompletionPercentage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("PartyName");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.Constituency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgPathId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("SvgPathId")
                        .IsUnique();

                    b.ToTable("Constituencies", t =>
                        {
                            t.HasCheckConstraint("CK_Constituency_TotalVoters", "TotalVoters >= 0");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotesReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ConstituencyId", "CandidateId")
                        .IsUnique();

                    b.ToTable("ElectionResults", t =>
                        {
                            t.HasCheckConstraint("CK_ElectionResult_Votes", "VotesReceived >= 0");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.ElectionResultSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("VotesReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("Status", "SubmittedAt");

                    b.HasIndex("ConstituencyId", "CandidateId", "Status");

                    b.ToTable("ElectionResultSubmissions", t =>
                        {
                            t.HasCheckConstraint("CK_ElectionResultSubmission_Votes", "VotesReceived >= 0");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Geopolitics.ConflictZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgPathId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegionName");

                    b.HasIndex("SvgPathId")
                        .IsUnique();

                    b.ToTable("ConflictZones");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Geopolitics.TimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Casualties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllingForce")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConflictZoneId", "Date");

                    b.ToTable("TimelineEvents", t =>
                        {
                            t.HasCheckConstraint("CK_TimelineEvent_Casualties", "Casualties >= 0");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedMatchId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CoordinateX")
                        .HasColumnType("REAL");

                    b.Property<float>("CoordinateY")
                        .HasColumnType("REAL");

                    b.Property<float?>("EndCoordinateX")
                        .HasColumnType("REAL");

                    b.Property<float?>("EndCoordinateY")
                        .HasColumnType("REAL");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("ExternalId IS NOT NULL");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status", "SubmittedAt");

                    b.HasIndex("MatchId", "PlayerId", "Minute");

                    b.ToTable("MatchEvents", t =>
                        {
                            t.HasCheckConstraint("CK_MatchEvent_EndX", "EndCoordinateX IS NULL OR EndCoordinateX BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_MatchEvent_EndY", "EndCoordinateY IS NULL OR EndCoordinateY BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_MatchEvent_Minute", "Minute >= 0");

                            t.HasCheckConstraint("CK_MatchEvent_X", "CoordinateX BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_MatchEvent_Y", "CoordinateY BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Team");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Budget.MegaProject", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Budget.BudgetSector", "BudgetSector")
                        .WithMany("MegaProjects")
                        .HasForeignKey("BudgetSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetSector");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.Candidate", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Election.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.ElectionResult", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Election.Candidate", "Candidate")
                        .WithMany("Results")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicWall.Api.Modules.Election.Constituency", "Constituency")
                        .WithMany("Results")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.ElectionResultSubmission", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Election.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicWall.Api.Modules.Election.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Geopolitics.TimelineEvent", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Geopolitics.ConflictZone", "ConflictZone")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("ConflictZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConflictZone");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.MatchEvent", b =>
                {
                    b.HasOne("MagicWall.Api.Modules.Sports.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicWall.Api.Modules.Sports.Player", "Player")
                        .WithMany("Events")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Budget.BudgetSector", b =>
                {
                    b.Navigation("MegaProjects");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.Candidate", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Election.Constituency", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Geopolitics.ConflictZone", b =>
                {
                    b.Navigation("TimelineEvents");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MagicWall.Api.Modules.Sports.Player", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
